version: "3"

services:
  api:
    image: lisa-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - "${LISA_STORAGE_PATH}:/home/lisa/data/storage"
    depends_on:
      - rabbitmq
      - worker
    networks:
      lisanet:
        ipv4_address: 172.42.0.10
    restart: on-failure

  worker:
    image: lisa-worker
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    environment:
      # - VPN=/vpn
      - API_SUCCESS_URL=${API_SUCCESS_URL}
      - API_FAILURE_URL=${API_FAILURE_URL}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?Env var MYSQL_PASSWORD is not set.}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:?Env var RABBITMQ_DEFAULT_PASS is not set.}
    volumes:
      - "${LISA_STORAGE_PATH}:/home/lisa/data/storage"
      - "${LISA_VPN_PATH}:/vpn"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - "net.ipv4.ping_group_range=0 2000000"
      - "net.ipv6.conf.all.disable_ipv6=0"
    cap_add:
      - NET_ADMIN
    networks:
      lisanet:
    restart: on-failure

  nginx:
    image: lisa-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        webhost: ${LISA_WEBHOST}:${LISA_PORT}
    ports:
      - ${LISA_PORT}:80
    depends_on:
      - api
    networks:
      lisanet:
        ipv4_address: 172.42.0.12

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=lisa
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:?Env var RABBITMQ_DEFAULT_PASS is not set.}
    ports:
      - 5672:5672
    networks:
      lisanet:
        ipv4_address: 172.42.0.13

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=lisa
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?Env var MYSQL_PASSWORD is not set.}
      - MYSQL_DATABASE=lisadb
    volumes:
      - "${LISA_DB_PATH}:/var/lib/mysql"
    networks:
      lisanet:
        ipv4_address: 172.42.0.14
    restart: always

networks:
  lisanet:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/24
